### ISSUE TITLE
Error: hostname() does not accepts arguments

### ISSUE THREAD

**Issue by sjfleck** [HpcGridRunner/HpcGridRunner#10]
**I'm attempting to use HpcGridRunner to speed up a couple commands as part my TransDecoder pipeline. I tested my blastp command on its own and it takes between 5 and 6 hours (with 16 threads). I wanted to see if I could speed this process up with your tool. My university uses the SLURM workload manager and we can only run a maximum of 1000 jobs at any given time. Here are my commands:**

module load gcc/6.3.0
module use -a /projects/academic/vaalbert/modulefiles/Allluas
module load ParaFly-0.1.0
module load perl-5.32.0
module load HpcGridRunner-1.0.2
module load ncbi-blast-2.11.0

/projects/academic/vaalbert/modulefiles/HpcGridRunner-1.0.2/BioIfx/hpc_FASTA_GridRunner.pl \
	--cmd_template "blastp -query __ QUERY_FILE __ -db $SPROT -max_target_seqs 1 -outfmt 6 -evalue 1e-5 > blastp.sprot.outfmt6" \
	--query_fasta $OUT/$SAMPLE.transdecoder_dir/longest_orfs.pep \
	-G /projects/academic/vaalbert/modulefiles/HpcGridRunner-1.0.2/hpc_conf/SLURM.test.conf \
	--parafly -N 150 -O blastp_sprot_results

**I also edited the "SLURM.test.conf". I hope this isn't where I messed things up. Our system requires -q and -p flags and I added a few other to send the jobs to a specific low-resource node:**

#template for a grid submission
#cmd=sbatch -p queue_name --mem=10000 --time=02:00:00 
cmd=sbatch --qos=general-compute --partition=general-compute --account=vaalbert --time=1:00:00 --nodes=1 --ntasks-per-node=8 --mem=23000 --mail-user=sjfleck@buffalo.edu --mail-type=ALL

**The command creates 4 directories (grp_0001-0004) with 591 fasta files divided between them. This is the final lines of my .err file:**

There are 591 jobs to run.
$VAR1 = {
          'max_nodes' => '4000',
          'grid' => 'SLURM',
          'cmds_per_node' => '20',
          'cmd' => 'sbatch --qos=general-compute --partition=general-compute --account=vaalbert --time=1:00:00 --nodes=1 --ntasks-per-node=8 --mem=23000 --mail-user=sjfleck@buffalo.edu --mail-type=ALL'
        };
hostname() does not accepts arguments (it used to silently discard any provided) at /projects/academic/vaalbert/modulefiles/HpcGridRunner-1.0.2/BioIfx/../PerlLib/HPC/FarmIt.pm line 91.

**any help for how I can fix this and have the program submit the 591 jobs would be very appreciated. Thank you!**

**Comment by angrybee** [comment]
PR #9 fixed it for me running trinity 2.12.0

**Comment by sjfleck** [comment]
thank you! That fixed it
