### ISSUE TITLE
Error during computing on the farm

### ISSUE THREAD

**Issue by patrick-douglas** [HpcGridRunner/HpcGridRunner#6]
Hello,
I'm getting the following error while running **Blastn** over HPC Grid Runner
My **walltime** are set to 99:00:00
CMDS: 720 / 57047  [36/36 nodes in use]   -no record of job_id 41239, setting as state unknown
-no record of job_id 41227, setting as state unknown
-no record of job_id 41253, setting as state unknown
-no record of job_id 41241, setting as state unknown
-no record of job_id 41248, setting as state unknown
-no record of job_id 41257, setting as state unknown
-no record of job_id 41256, setting as state unknown
-no record of job_id 41235, setting as state unknown
-no record of job_id 41240, setting as state unknown
-no record of job_id 41242, setting as state unknown
-no record of job_id 41254, setting as state unknown
-no record of job_id 41249, setting as state unknown
-no record of job_id 41224, setting as state unknown
-no record of job_id 41236, setting as state unknown
-no record of job_id 41231, setting as state unknown
-no record of job_id 41244, setting as state unknown
-no record of job_id 41251, setting as state unknown
-no record of job_id 41223, setting as state unknown
-no record of job_id 41230, setting as state unknown
-no record of job_id 41222, setting as state unknown
-no record of job_id 41225, setting as state unknown
-no record of job_id 41255, setting as state unknown
-no record of job_id 41233, setting as state unknown
-no record of job_id 41246, setting as state unknown
-no record of job_id 41245, setting as state unknown
-no record of job_id 41247, setting as state unknown
-no record of job_id 41228, setting as state unknown
-no record of job_id 41229, setting as state unknown
-no record of job_id 41252, setting as state unknown
-no record of job_id 41238, setting as state unknown
-no record of job_id 41234, setting as state unknown
-no record of job_id 41243, setting as state unknown
-no record of job_id 41232, setting as state unknown
-no record of job_id 41226, setting as state unknown
-no record of job_id 41250, setting as state unknown
-no record of job_id 41237, setting as state unknown
....
Running with the following command line 
./hpc_FASTA_GridRunner.pl --cmd_template "blastn -query __QUERY_FILE__ -db /media/me/BACK_UP_1/blast_db/db_nucl/amphibia_reptilia_actinopterygii_mammalia_aves.fasta -max_target_seqs 1 -outfmt 6 -evalue 1e-3 -num_threads 2" --query_fasta /home/me/blast+/todos_um_e_dois.fasta -G /home/me/HpcGridRunner/PBS.blast+.conf --parafly -N 10 -O todos_um_dois_vs_ncbi-db_nucl

**EDIT**
When I run **top** in **node** to view the **blastn** proccess it appears as **D** status (uninterruptible sleep)
see my **top** screen in the attached screenshot:
![screenshot_2017-09-06_21-27-44](https://user-images.githubusercontent.com/24271907/30140360-567b6a5c-934a-11e7-9b76-275c9030d91c.png)

**Comment by patrick-douglas** [comment]
I recently solved this problem, my **Blastn database** are too large (~800GB) and are stored in other **hard drive NTFS formated** instead OS hard drive (SSHD), so I mounted over **NFS** the HD in each node to give access to the database. However in Linux Mint the **NTFS HD** are read/write protected (I don't have idea why). So the **Node** fail to read the **database** and the **task** stay sleeping forever.
I solved by formatting HD to Ext4 file system, copy the **blastn database** again e change the permission by running **chmod -R me:me**.

**Comment by patrick-douglas** [comment]
I'm receiving the same error, **-no record of job_id** when I try to run BlastX in a large dataset, because the nodes delay to finish the commands, and HPC grid runner do not wait the finish the jobs.
What to do?

**Comment by brianjohnhaas** [comment]
You'll want to take a look at the module here:

 GITHUB/HpcGridRunner/PerlLib/HPC

that corresponds to your grid computing system and see the method

    job_running_or_pending_on_grid()

  It might need a little hacking to see that it can interact properly with
your grid to poll jobs on the system.

On Fri, Sep 22, 2017 at 6:16 PM, Patrick Douglas <notifications@github.com>
wrote:
>
> I'm receiving the same error, -no record of job_id when I try to run
BlastX in a large dataset, because the nodes delay to finish the commands,
and HPC grid runner do not wait the finish the jobs.
> What to do?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.




--
--
Brian J. Haas
The Broad Institute
http://broadinstitute.org/~bhaas

**Comment by patrick-douglas** [comment]
I Discovered why the commands finish with error, **-no record of job_id** when I try to run BlastX in a large data-set, It is because the nodes access the blast database trhought network and my "homemade" cluster does not have a High speed network connection. 
To solve this issue I just create a copy of **ncbi-nr** database locally in each node using a common directory in all nodes,(e.g **/db/ncbi-nr**).
